### ISSUE TITLE
Package pillow-simd?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/pillow-feedstock#103]
Hey @conda-forge/pillow 

I'm co-maintaining the torchvision feedstock, and recently noticed that they are actually [depending](https://github.com/pytorch/vision/blob/v0.11.2/setup.py#L73)** on `pillow-simd`, a SIMD-optimized [fork](https://github.com/uploadcare/pillow-simd) of pillow. Here is a performance comparison that - AFAICT - is even [hosted](https://python-pillow.org/pillow-perf/) on the main pillow website, where SSE4 already achieves substantial speedups, and AVX2 even more so, on the order of a factor of 5x.

Given that the sources are very very similar, I'd be wary of having this in a separate feedstock (requiring a mutex etc.), and also pillow-simd formulates their policy:
> Pillow-SIMD is "following" Pillow. Pillow-SIMD versions are 100% compatible drop-in replacements for Pillow of the same version. For example, Pillow-SIMD `3.2.0.post3` is a drop-in replacement for Pillow `3.2.0`, and Pillow-SIMD `3.3.3.post0` — for Pillow `3.3.3`.

The downside of building both outputs in this feedstock would be that new pillow releases would have to _also_ wait on the corresponding pillow-simd release.

Any thoughts?

CC @conda-forge/torchvision @conda-forge/core

** conditional on availability, with fallback to pillow

**Comment by ocefpaf** [comment]
Is pillow-simd at PyPI? I could not find it. (Not important here, just curious.)

I think that the approach here should be a different feedstock with  a `run_constrained` line to avoid installing both in the same environment. What do you think @isuruf?

**Comment by xhochy** [comment]
Different feedstock sounds like a good idea. Both of them could have a metapackage that provides, e.g. `pillow-meta` with a `{{ pin_subpackage(…, exact=True) }}` for the corresponding implementation.

**Comment by h-vetinari** [comment]
> Both of them could have a metapackage that provides, e.g. `pillow-meta` with a `{{ pin_subpackage(…, exact=True) }}` for the corresponding implementation.

Would we need repopatches for the old pillow releases? Or just add a version constraint? 9.0.0 was recently released, so that'd be a decent opportunity.

Do I understand you correctly that this would roughly be the structure?
```
# pillow-feedstock/recipe/meta.yaml
...
outputs:
  - name: pillow
    build:
      [...]
      track_features:
        - ?
      run_exports:
        - pillow-meta =*=*default

  - name: pillow-meta
    build:
      string: "{{ build_num }}_default"
      track_features:
        - ?
    requirements:
      host:
        - {{ pin_subpackage("pillow", exact=True) }}
      run_constrained:
        - ?
```
```
# pillow-simd-feedstock/recipe/meta.yaml
...
outputs:
  - name: pillow-simd
    build:
      [...]
      track_features:
        - ?
      run_exports:
        - pillow-meta =*=*simd

  - name: pillow-meta
    build:
      string: "{{ build_num }}_simd"
      track_features:
        - ?
    requirements:
      host:
        - {{ pin_subpackage("pillow-simd", exact=True) }}
      run_constrained:
        - ?
```
